# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YQ6j3gufoMKB8i4g5rY2-tXoFsbOG4WU
"""

# app.py — NovaPay Fraud Detection Platform (Random Forest)
import os
import json
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st
import joblib

import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier


# ----------------------------
# Paths
# ----------------------------
APP_DIR = Path(__file__).parent
DATA_DIR = APP_DIR / "Data"
MODELS_DIR = APP_DIR / "Models"

MODEL_PATH = MODELS_DIR / "rf_fraud_model.joblib"
FEATURES_PATH = MODELS_DIR / "rf_features.json"


# ----------------------------
# UI Config
# ----------------------------
st.set_page_config(page_title="NovaPay | AI Fraud Detection", page_icon="🛡️", layout="wide")


CUSTOM_CSS = """
<style>
.block-container { padding-top: 1.5rem; padding-bottom: 2rem; }
div[data-testid="stSidebarContent"] { padding-top: 1rem; }

.hero {
  padding: 22px;
  border-radius: 18px;
  background: linear-gradient(135deg, rgba(79,70,229,0.25), rgba(16,185,129,0.12));
  border: 1px solid rgba(255,255,255,0.08);
}
.hero h1 { margin-bottom: 0.2rem; }

.badge {
  display: inline-block;
  padding: 6px 10px;
  border-radius: 999px;
  font-size: 12px;
  background: rgba(255,255,255,0.08);
  border: 1px solid rgba(255,255,255,0.10);
}

.card, .panel {
  border-radius: 16px;
  padding: 16px;
  background: rgba(255,255,255,0.04);
  border: 1px solid rgba(255,255,255,0.08);
}
.card h3, .panel h3 { margin-top: 0; }

.kpi-grid { display:flex; gap:12px; flex-wrap:wrap; margin-top:10px; }
.kpi-card{
  flex: 1 1 160px;
  padding:14px;
  border-radius:16px;
  background: rgba(255,255,255,0.04);
  border: 1px solid rgba(255,255,255,0.08);
}
.kpi-title{ font-size:12px; opacity:0.75; }
.kpi-value{ font-size:22px; font-weight:700; }
.kpi-sub{ font-size:12px; opacity:0.8; }

.smallmuted { opacity: 0.8; font-size: 13px; }
hr.soft { border:none; height:1px; background:rgba(255,255,255,0.08); margin:12px 0; }

.tag{
  display:inline-block;
  padding:6px 10px;
  margin-right:6px;
  border-radius:999px;
  font-size:12px;
  background:rgba(255,255,255,0.08);
  border:1px solid rgba(255,255,255,0.10);
}
</style>
"""
st.markdown(CUSTOM_CSS, unsafe_allow_html=True)


# ----------------------------
# Feature prep / encoding
# ----------------------------
def prepare_features_for_model(df: pd.DataFrame, target: str = "is_fraud"):
    """
    Takes raw/feature CSV that still contains timestamp + categoricals,
    and returns X (numeric matrix) + y (labels).
    """
    df = df.copy()

    if target not in df.columns:
        raise ValueError(f"Target column '{target}' not found in training CSV.")

    y = df[target].astype(int).values
    X = df.drop(columns=[target])

    # ID columns should NOT be used as model features
    ID_COLS = ["transaction_id", "txn_id", "transactionId", "TransactionID"]
    X = X.drop(columns=[c for c in ID_COLS if c in X.columns], errors="ignore")


    # Handle timestamp -> time features
    if "timestamp" in X.columns:
        ts = pd.to_datetime(X["timestamp"], errors="coerce", utc=True)
        X["hour"] = ts.dt.hour.fillna(0).astype(int)
        X["dayofweek"] = ts.dt.dayofweek.fillna(0).astype(int)
        X["month"] = ts.dt.month.fillna(0).astype(int)
        X["is_weekend"] = (ts.dt.dayofweek >= 5).fillna(False).astype(int)
        X = X.drop(columns=["timestamp"])

    # One-hot encode categoricals + bools
    cat_cols = X.select_dtypes(include=["object", "bool"]).columns.tolist()
    if len(cat_cols) > 0:
        X = pd.get_dummies(X, columns=cat_cols, drop_first=False)

    # Clean numeric issues
    X = X.replace([np.inf, -np.inf], np.nan).fillna(0)

    return X, y


def align_features(X_any: pd.DataFrame, feature_list: list[str]) -> pd.DataFrame:
    """
    Ensures X has exactly the columns used in training, in the same order.
    Missing columns are created as 0, extra columns are dropped.
    """
    X = X_any.copy()
    for col in feature_list:
        if col not in X.columns:
            X[col] = 0
    X = X[feature_list]
    return X


# ----------------------------
# Model load/save
# ----------------------------
def load_model_and_features():
    if MODEL_PATH.exists() and FEATURES_PATH.exists():
        model = joblib.load(MODEL_PATH)
        with open(FEATURES_PATH, "r", encoding="utf-8") as f:
            features = json.load(f)
        return model, features, True
    return None, [], False


def save_model_and_features(model, features: list[str]):
    MODELS_DIR.mkdir(exist_ok=True)
    joblib.dump(model, MODEL_PATH)
    with open(FEATURES_PATH, "w", encoding="utf-8") as f:
        json.dump(features, f, indent=2)


# ----------------------------
# Scoring + risk tiers
# ----------------------------
def risk_tier(prob: float) -> str:
    if prob >= 0.80:
        return "Critical"
    if prob >= 0.60:
        return "High"
    if prob >= 0.35:
        return "Medium"
    return "Low"


def score_df(df_in: pd.DataFrame, model, features: list[str], threshold: float):
    df = df_in.copy()
    ID_COLS = ["transaction_id", "txn_id", "transactionId", "TransactionID"]
    df = df.drop(columns=[c for c in ID_COLS if c in df.columns], errors="ignore")


    # If user uploads raw data with timestamp/categoricals, we must encode it
    # similarly to training (but WITHOUT target)
    if "timestamp" in df.columns:
        ts = pd.to_datetime(df["timestamp"], errors="coerce", utc=True)
        df["hour"] = ts.dt.hour.fillna(0).astype(int)
        df["dayofweek"] = ts.dt.dayofweek.fillna(0).astype(int)
        df["month"] = ts.dt.month.fillna(0).astype(int)
        df["is_weekend"] = (ts.dt.dayofweek >= 5).fillna(False).astype(int)
        df = df.drop(columns=["timestamp"])

    cat_cols = df.select_dtypes(include=["object", "bool"]).columns.tolist()
    if len(cat_cols) > 0:
        df = pd.get_dummies(df, columns=cat_cols, drop_first=False)

    df = df.replace([np.inf, -np.inf], np.nan).fillna(0)

    X = align_features(df, features)

    # RF supports predict_proba
    prob = model.predict_proba(X)[:, 1]
    out = df_in.copy()
    out["fraud_probability"] = prob
    out["fraud_flag"] = (out["fraud_probability"] >= threshold).astype(int)
    out["risk_tier"] = out["fraud_probability"].apply(risk_tier)

    return out


def generate_action_recommendation(row: pd.Series):
    reasons = []
    actions = []

    # These are simple rules to SOUND like an analyst assistant
    if row.get("fraud_probability", 0) >= 0.80:
        actions.append("Hold transaction and escalate to fraud queue immediately.")
        actions.append("Request step-up authentication (OTP/biometric) if allowed.")
    elif row.get("fraud_probability", 0) >= 0.60:
        actions.append("Flag for manual review before settlement.")
        actions.append("Monitor linked customer/device for rapid follow-up attempts.")
    else:
        actions.append("Allow transaction but keep monitoring risk trend.")

    # Common signals (only add if the column exists)
    if "ip_risk_score" in row and row["ip_risk_score"] >= 0.7:
        reasons.append("High IP risk score")
    if "txn_velocity_1h" in row and row["txn_velocity_1h"] >= 5:
        reasons.append("High 1-hour velocity")
    if "txn_velocity_24h" in row and row["txn_velocity_24h"] >= 15:
        reasons.append("High 24-hour velocity")
    if "account_age_days" in row and row["account_age_days"] <= 30:
        reasons.append("Very new account age")
    if "corridor_risk" in row and row["corridor_risk"] >= 0.6:
        reasons.append("High-risk corridor")

    if len(reasons) == 0:
        reasons.append("Overall feature pattern matched historical fraud behaviour in the model.")

    return reasons, actions


def metric_row(scored_df: pd.DataFrame):
    total = len(scored_df)
    flagged = int((scored_df["fraud_flag"] == 1).sum())
    crit = int((scored_df["risk_tier"] == "Critical").sum())
    high = int((scored_df["risk_tier"] == "High").sum())
    avg_prob = float(scored_df["fraud_probability"].mean()) if total else 0.0
    return total, flagged, crit, high, avg_prob


# ----------------------------
# Sidebar
# ----------------------------
st.sidebar.title("🧭 NovaPay Console")

page = st.sidebar.radio(
    "Navigate",
    ["🏠 Dashboard", "🧪 Batch Scoring", "🎯 Single Score", "🧠 Explainability", "📡 Monitoring"],
    index=0
)

st.sidebar.markdown("---")
threshold = st.sidebar.slider("Fraud threshold", 0.10, 0.90, 0.40, 0.05)
st.sidebar.caption("Higher threshold = fewer alerts, lower threshold = catch more fraud.")

st.sidebar.markdown("---")
st.sidebar.subheader("⚙️ Model Control")

model, features, loaded = load_model_and_features()

# List CSVs in Data folder
DATA_DIR.mkdir(exist_ok=True)
feature_csvs = sorted(DATA_DIR.glob("*.csv"))

if len(feature_csvs) == 0:
    st.sidebar.error("No CSV found in the Data folder.")
    csv_choice = None
else:
    csv_choice = st.sidebar.selectbox(
        "Training data source (Data folder)",
        feature_csvs,
        format_func=lambda p: p.name
    )

train_clicked = st.sidebar.button("Train / Refresh Model")

if train_clicked:
    if csv_choice is None:
        st.sidebar.error("Please add a training CSV into the Data folder first.")
    else:
        try:
            df_train = pd.read_csv(csv_choice)
            X_train, y_train = prepare_features_for_model(df_train, target="is_fraud")

            rf = RandomForestClassifier(
                n_estimators=300,
                max_depth=12,
                random_state=42,
                n_jobs=-1
            )
            rf.fit(X_train, y_train)

            feature_list = X_train.columns.tolist()
            save_model_and_features(rf, feature_list)

            st.sidebar.success("✅ Model trained and saved successfully.")
            st.rerun()  # IMPORTANT: refresh so loaded=True immediately

        except Exception as e:
            st.sidebar.error(f"Training failed: {e}")


# Reload after potential rerun/training
model, features, loaded = load_model_and_features()


# ----------------------------
# Pages
# ----------------------------
if page == "🏠 Dashboard":
    st.markdown(
        """
        <div class="hero">
          <span class="badge">AI-Assisted Fraud Defense</span>
          <h1>🛡️ NovaPay Fraud Detection Platform</h1>
          <div class="smallmuted">
            Upload transactions • Score fraud probability • Explain decisions • Monitor risk
          </div>
        </div>
        """,
        unsafe_allow_html=True
    )

    c1, c2, c3 = st.columns([1.2, 1, 1])

    with c1:
        st.markdown('<div class="card"><h3>What this app does</h3>', unsafe_allow_html=True)
        st.write(
            """
            - Scores transactions with a trained **Random Forest** fraud model
            - Produces **risk tiers** (Low → Critical) + recommended actions
            - Provides a clean workflow for fraud analysts and reporting
            """
        )
        st.markdown("</div>", unsafe_allow_html=True)

    with c2:
        st.markdown('<div class="card"><h3>Model Status</h3>', unsafe_allow_html=True)
        if loaded:
            st.success("Model is ready ✅")
            st.write(f"Features loaded: **{len(features)}**")
            st.caption("Feature list example includes columns like those in rf_features.json.")
        else:
            st.warning("Model not ready yet.")
            st.write("Train from the sidebar (Model Control).")
        st.markdown("</div>", unsafe_allow_html=True)

    with c3:
        st.markdown('<div class="card"><h3>Quick Start</h3>', unsafe_allow_html=True)
        st.write(
            """
            1) Train/Refresh model from sidebar
            2) Go to **Batch Scoring**
            3) Upload a CSV
            4) View KPIs + risk tiers + download results
            """
        )
        st.markdown("</div>", unsafe_allow_html=True)

    st.markdown("### 🔎 Quick check")
    st.info("If you trained successfully, Batch Scoring will stop showing 'Model not ready'.")


elif page == "🧪 Batch Scoring":
    st.markdown("## 🧪 Batch Scoring")
    st.caption("Upload a CSV → score fraud probability → review highest-risk cases → download results.")

    if not loaded:
        st.error("Model not ready yet. Train it from the sidebar first.")
        st.stop()

    st.markdown(
        """
        <div class="panel">
          <h3>📂 Upload Transactions</h3>
          <div class="smallmuted">Upload feature CSV (or raw CSV — timestamp/categoricals will be encoded).</div>
        </div>
        """,
        unsafe_allow_html=True
    )

    uploaded = st.file_uploader("Upload CSV", type=["csv"])

    if uploaded is None:
        st.info("Click **Browse files** to upload your CSV.")
        st.stop()

    df_in = pd.read_csv(uploaded)

    left, right = st.columns([1.4, 1])

    with left:
        st.markdown("### 👀 Preview")
        st.dataframe(df_in.head(25), use_container_width=True)

    with right:
        st.markdown("### ⚙️ Options")
        top_n = st.slider("Show top risky rows", 10, 200, 50, 10)
        show_only_flagged = st.checkbox("Show only flagged fraud", value=False)

    with st.spinner("Scoring transactions…"):
        scored = score_df(df_in.drop(columns=["is_fraud"], errors="ignore"), model, features, threshold=threshold)

    if show_only_flagged:
        view_df = scored[scored["fraud_flag"] == 1].copy()
    else:
        view_df = scored.copy()

    total, flagged, crit, high, avg_prob = metric_row(scored)

    st.markdown(
        f"""
        <div class="kpi-grid">
          <div class="kpi-card"><div class="kpi-title">Transactions</div><div class="kpi-value">{total:,}</div><div class="kpi-sub">Rows scored</div></div>
          <div class="kpi-card"><div class="kpi-title">Flagged</div><div class="kpi-value">{flagged:,}</div><div class="kpi-sub">threshold {threshold:.2f}</div></div>
          <div class="kpi-card"><div class="kpi-title">Critical</div><div class="kpi-value">{crit:,}</div><div class="kpi-sub">risk_tier</div></div>
          <div class="kpi-card"><div class="kpi-title">High</div><div class="kpi-value">{high:,}</div><div class="kpi-sub">risk_tier</div></div>
          <div class="kpi-card"><div class="kpi-title">Average Risk</div><div class="kpi-value">{avg_prob:.3f}</div><div class="kpi-sub">mean probability</div></div>
        </div>
        """,
        unsafe_allow_html=True
    )

    st.markdown("### 📊 Risk Breakdown")
    tier_counts = scored["risk_tier"].value_counts().reindex(["Low", "Medium", "High", "Critical"]).fillna(0)

    c1, c2 = st.columns([1, 1.2])
    with c1:
        fig = plt.figure(figsize=(6, 4))
        plt.bar(tier_counts.index.astype(str), tier_counts.values)
        plt.title("Risk Tier Distribution")
        plt.xlabel("Tier")
        plt.ylabel("Count")
        st.pyplot(fig)

    with c2:
        st.markdown("#### 🔥 Top Risk Cases")
        top_risky = scored.sort_values("fraud_probability", ascending=False).head(top_n)
        st.dataframe(top_risky, use_container_width=True)

    st.markdown("### 🧾 Scored Output (preview)")
    st.dataframe(view_df.head(200), use_container_width=True)

    st.markdown("### ⬇️ Export Results")
    colA, colB = st.columns(2)

    with colA:
        st.download_button(
            "Download FULL scored CSV",
            data=scored.to_csv(index=False).encode("utf-8"),
            file_name="novapay_scored_full.csv",
            mime="text/csv"
        )

    with colB:
        flagged_df = scored[scored["fraud_flag"] == 1]
        st.download_button(
            "Download ONLY flagged fraud",
            data=flagged_df.to_csv(index=False).encode("utf-8"),
            file_name="novapay_scored_flagged_only.csv",
            mime="text/csv"
        )


elif page == "🎯 Single Score":
    st.title("🎯 Single Transaction Scoring")
    st.caption("Enter key fields → model scores fraud probability → assistant suggests actions.")

    if not loaded:
        st.warning("Model not ready. Train it from sidebar first.")
        st.stop()

    left, right = st.columns([1.1, 1])

    with left:
        st.markdown('<div class="card"><h3>Transaction Inputs</h3>', unsafe_allow_html=True)
        amount_usd = st.number_input("Amount (USD)", min_value=0.0, value=250.0, step=10.0)
        ip_risk_score = st.slider("IP risk score", 0.0, 1.0, 0.35, 0.01)
        transaction_id = st.text_input("Transaction ID", value="TXN-000001")


        # device_trust_score can be negative in your data, so allow negatives
        device_trust_score = st.slider("Device trust score", -1.0, 1.0, 0.70, 0.01)

        account_age_days = st.number_input("Account age (days)", min_value=0, value=120, step=1)
        txn_velocity_1h = st.number_input("Txn velocity (1h)", min_value=0, value=1, step=1)
        txn_velocity_24h = st.number_input("Txn velocity (24h)", min_value=0, value=3, step=1)
        corridor_risk = st.slider("Corridor risk", 0.0, 1.0, 0.25, 0.01)
        location_mismatch = st.checkbox("Location mismatch?", value=False)
        new_device = st.checkbox("New device?", value=False)
        run = st.button("🧠 Score now")
        st.markdown("</div>", unsafe_allow_html=True)

    with right:
        st.markdown('<div class="card"><h3>AI Assistant</h3>', unsafe_allow_html=True)
        st.write("This panel explains the score in simple analyst language.")
        st.markdown("</div>", unsafe_allow_html=True)

        if run:
            row = pd.DataFrame([{
                "transaction_id": transaction_id,
                "amount_usd": amount_usd,
                "amount_src": amount_usd,
                "ip_risk_score": ip_risk_score,
                "device_trust_score": device_trust_score,
                "account_age_days": int(account_age_days),
                "txn_velocity_1h": int(txn_velocity_1h),
                "txn_velocity_24h": int(txn_velocity_24h),
                "corridor_risk": corridor_risk,
                "location_mismatch": bool(location_mismatch),
                "new_device": bool(new_device),
            }])

            scored_one = score_df(row, model, features, threshold=threshold)
            prob = float(scored_one["fraud_probability"].iloc[0])
            flag = int(scored_one["fraud_flag"].iloc[0])
            tier = str(scored_one["risk_tier"].iloc[0])

            st.markdown("### Result")
            st.write(f"**Fraud probability:** `{prob:.4f}`")
            st.write(f"**Risk tier:** **{tier}**  |  **Threshold:** `{threshold:.2f}`")

            if flag == 1:
                st.error("⚠️ Decision: FLAG AS FRAUD (send to review)")
            else:
                st.success("✅ Decision: ALLOW (monitor)")

            reasons, actions = generate_action_recommendation(scored_one.iloc[0])

            st.markdown("### Why this was flagged (signals)")
            for r in reasons:
                st.write(f"• {r}")

            st.markdown("### Recommended actions")
            for a in actions:
                st.write(f"✅ {a}")


elif page == "🧠 Explainability":
    st.title("🧠 Explainability (SHAP)")
    st.write("Global explanations for the Random Forest fraud model (precomputed SHAP).")

    shap_file = MODELS_DIR / "shap_values_rf.npy"
    x_test_file = MODELS_DIR / "X_test_for_shap.csv"

    if not (shap_file.exists() and x_test_file.exists()):
        st.info(
            "SHAP files not found in Models/.\n\n"
            "Add these files to Models/:\n"
            "- shap_values_rf.npy\n"
            "- X_test_for_shap.csv (features only, NO is_fraud)\n"
        )
        st.stop()

    shap_values = np.load(shap_file, allow_pickle=True)
    X_test = pd.read_csv(x_test_file)

    # Safety: SHAP test matrix should not include target
    if "is_fraud" in X_test.columns:
        X_test = X_test.drop(columns=["is_fraud"])

    # If saved SHAP is list per class, pick fraud class
    if isinstance(shap_values, list):
        shap_values = shap_values[1]

    # Validate dimensions
    if shap_values.shape[1] != X_test.shape[1]:
        st.error(
            f"Mismatch: SHAP has {shap_values.shape[1]} features, "
            f"but X_test has {X_test.shape[1]} columns.\n\n"
            "Fix: regenerate SHAP using the exact same X_test you saved."
        )
        st.stop()

    st.subheader("Top features (mean |SHAP|)")
    mean_abs = np.abs(shap_values).mean(axis=0)
    fi = (
        pd.DataFrame({"feature": X_test.columns, "mean_abs_shap": mean_abs})
        .sort_values("mean_abs_shap", ascending=False)
    )

    st.dataframe(fi.head(30), use_container_width=True)

    st.subheader("Bar chart (Top 20)")
    top20 = fi.head(20).iloc[::-1]
    fig = plt.figure(figsize=(9, 6))
    plt.barh(top20["feature"], top20["mean_abs_shap"])
    plt.xlabel("Mean |SHAP value|")
    plt.title("Top 20 Features by Mean |SHAP| (Fraud class)")
    st.pyplot(fig)



elif page == "📡 Monitoring":
    st.title("📡 Monitoring (basic)")
    st.write("Lightweight drift-style checks (demo-friendly).")

    if not loaded:
        st.warning("Model not ready. Train it from sidebar first.")
        st.stop()

    baseline_candidates = sorted(DATA_DIR.glob("*.csv"))
    if len(baseline_candidates) == 0:
        st.info("Add a baseline CSV into Data/ to enable monitoring.")
        st.stop()

    baseline_path = st.selectbox("Choose baseline CSV (Data folder)", baseline_candidates, format_func=lambda p: p.name)
    new_file = st.file_uploader("Upload NEW CSV for comparison", type=["csv"])

    base_df = pd.read_csv(baseline_path).drop(columns=["is_fraud"], errors="ignore")
    if new_file is None:
        st.caption("Upload a new dataset to compare distributions.")
        st.stop()

    new_df = pd.read_csv(new_file).drop(columns=["is_fraud"], errors="ignore")

    # Compare only common numeric columns
    common_cols = list(set(base_df.columns).intersection(set(new_df.columns)))
    base_num = base_df[common_cols].select_dtypes(include=[np.number])
    new_num = new_df[common_cols].select_dtypes(include=[np.number])

    if base_num.shape[1] == 0:
        st.info("No common numeric columns found for monitoring.")
        st.stop()

    col = st.selectbox("Choose a numeric feature", list(base_num.columns))

    fig = plt.figure(figsize=(8, 4))
    plt.hist(base_num[col].dropna(), bins=30, alpha=0.6, label="Baseline")
    plt.hist(new_num[col].dropna(), bins=30, alpha=0.6, label="New")
    plt.title(f"Distribution comparison: {col}")
    plt.legend()
    st.pyplot(fig)