# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18vUVb6sf8RzXJe6hiWm92Cr_vAqrhpPH
"""

# app.py
# ==========================================================
# NovaPay Fraud Detection AI Platform (FAST VERSION)
# ==========================================================
# Optimized for:
# - Speed
# - Clear KPIs
# - Academic evaluation
# - Minimal recomputation
# ==========================================================

from pathlib import Path
import json
import numpy as np
import pandas as pd
import streamlit as st
import joblib
import matplotlib.pyplot as plt

# ==========================================================
# CONFIG
# ==========================================================
APP_DIR = Path(__file__).parent
DATA_DIR = APP_DIR / "Data"
MODELS_DIR = APP_DIR / "Models"

MODEL_PATH = MODELS_DIR / "rf_fraud_model.joblib"
FEATURES_PATH = MODELS_DIR / "rf_features.json"

st.set_page_config(
    page_title="NovaPay Fraud Detection",
    page_icon="🛡️",
    layout="wide"
)

# ==========================================================
# STYLE (lightweight)
# ==========================================================
st.markdown("""
<style>
.block-container { padding-top: 1.2rem; }
.card {
    background: rgba(255,255,255,0.04);
    border-radius: 14px;
    padding: 16px;
    border: 1px solid rgba(255,255,255,0.08);
}
.kpi {
    font-size: 28px;
    font-weight: 700;
}
.sub {
    font-size: 13px;
    opacity: 0.75;
}
</style>
""", unsafe_allow_html=True)

# ==========================================================
# CACHED LOADERS (CRITICAL FOR SPEED)
# ==========================================================
@st.cache_resource
def load_model():
    return joblib.load(MODEL_PATH)

@st.cache_resource
def load_features():
    with open(FEATURES_PATH, "r") as f:
        return json.load(f)

@st.cache_data
def load_csv(file):
    return pd.read_csv(file)

# ==========================================================
# FEATURE PREP (LIGHT + CONSISTENT)
# ==========================================================
IMPORTANT_FEATURES = [
    "amount_usd",
    "ip_risk_score",
    "device_trust_score",
    "txn_velocity_1h",
    "txn_velocity_24h",
    "account_age_days",
    "corridor_risk",
    "location_mismatch",
    "new_device"
]

def prepare_features(df: pd.DataFrame, feature_list: list):
    X = df.copy()

    # Drop target if present
    X = X.drop(columns=["is_fraud"], errors="ignore")

    # Keep only important features
    X = X[[c for c in feature_list if c in X.columns]]

    # Fill missing columns
    for col in feature_list:
        if col not in X.columns:
            X[col] = 0

    # Clean
    X = X.replace([np.inf, -np.inf], np.nan).fillna(0)

    return X[feature_list]

# ==========================================================
# SCORING
# ==========================================================
def score_transactions(df, model, features, threshold):
    X = prepare_features(df, features)
    probs = model.predict_proba(X)[:, 1]

    out = df.copy()
    out["fraud_probability"] = probs
    out["fraud_flag"] = (probs >= threshold).astype(int)

    out["risk_tier"] = pd.cut(
        probs,
        bins=[0, 0.35, 0.60, 0.80, 1.0],
        labels=["Low", "Medium", "High", "Critical"]
    )

    return out

# ==========================================================
# SIDEBAR
# ==========================================================
st.sidebar.title("🧭 NovaPay Console")

page = st.sidebar.radio(
    "Navigation",
    ["Dashboard", "Batch Scoring", "Single Transaction"],
)

threshold = st.sidebar.slider(
    "Fraud Threshold",
    0.1, 0.99, 0.93, 0.01
)

# ==========================================================
# LOAD MODEL
# ==========================================================
if not MODEL_PATH.exists():
    st.error("❌ Model not found. Please train and save your RF model.")
    st.stop()

model = load_model()
features = IMPORTANT_FEATURES

# ==========================================================
# DASHBOARD
# ==========================================================
if page == "Dashboard":
    st.markdown("## 🛡️ NovaPay Fraud Detection Dashboard")

    st.markdown("""
    <div class="card">
    This system detects **high-risk financial transactions** using a
    **Random Forest classifier** optimized for **precision-critical fraud detection**.
    </div>
    """, unsafe_allow_html=True)

    st.markdown("### 🎯 Model Objectives")
    st.write("""
    - Precision = **1.00** (no false positives)
    - Recall ≈ **0.90**
    - Optimized threshold selection
    """)

# ==========================================================
# BATCH SCORING
# ==========================================================
elif page == "Batch Scoring":
    st.markdown("## 🧪 Batch Fraud Scoring")

    uploaded = st.file_uploader("Upload transaction CSV", type=["csv"])
    if uploaded is None:
        st.info("Upload a CSV file to begin.")
        st.stop()

    df = load_csv(uploaded)

    if st.button("🚀 Run Fraud Scoring"):
        with st.spinner("Scoring transactions..."):
            scored = score_transactions(df, model, features, threshold)

        # ================= KPIs =================
        total = len(scored)
        flagged = scored["fraud_flag"].sum()
        critical = (scored["risk_tier"] == "Critical").sum()
        avg_prob = scored["fraud_probability"].mean()

        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Transactions", total)
        c2.metric("Flagged", flagged)
        c3.metric("Critical", critical)
        c4.metric("Avg Risk", f"{avg_prob:.3f}")

        # ================= Plot =================
        st.markdown("### 📊 Risk Distribution")
        fig, ax = plt.subplots()
        scored["risk_tier"].value_counts().plot(kind="bar", ax=ax)
        st.pyplot(fig)

        # ================= Table =================
        st.markdown("### 🔍 Top High-Risk Transactions")
        st.dataframe(
            scored.sort_values("fraud_probability", ascending=False).head(50),
            use_container_width=True
        )

        # ================= Export =================
        st.download_button(
            "⬇️ Download Scored CSV",
            scored.to_csv(index=False).encode("utf-8"),
            "novapay_scored.csv",
            "text/csv"
        )

# ==========================================================
# SINGLE TRANSACTION
# ==========================================================
elif page == "Single Transaction":
    st.markdown("## 🎯 Single Transaction Scoring")

    with st.form("single_txn"):
        amount = st.number_input("Amount (USD)", 0.0, 100000.0, 250.0)
        ip = st.slider("IP Risk Score", 0.0, 1.0, 0.4)
        device = st.slider("Device Trust Score", 0.0, 1.0, 0.7)
        v1 = st.number_input("Txn Velocity (1h)", 0, 100, 1)
        v24 = st.number_input("Txn Velocity (24h)", 0, 200, 3)
        age = st.number_input("Account Age (days)", 0, 5000, 120)
        corridor = st.slider("Corridor Risk", 0.0, 1.0, 0.3)
        loc = st.checkbox("Location Mismatch")
        new_dev = st.checkbox("New Device")

        submitted = st.form_submit_button("Score Transaction")

    if submitted:
        row = pd.DataFrame([{
            "amount_usd": amount,
            "ip_risk_score": ip,
            "device_trust_score": device,
            "txn_velocity_1h": v1,
            "txn_velocity_24h": v24,
            "account_age_days": age,
            "corridor_risk": corridor,
            "location_mismatch": int(loc),
            "new_device": int(new_dev)
        }])

        scored = score_transactions(row, model, features, threshold)
        prob = scored["fraud_probability"].iloc[0]
        tier = scored["risk_tier"].iloc[0]

        st.metric("Fraud Probability", f"{prob:.4f}")
        st.metric("Risk Tier", tier)

        if prob >= threshold:
            st.error("🚨 FLAGGED AS FRAUD")
        else:
            st.success("✅ ALLOWED")

# ==========================================================
# END
# ==========================================================