# -*- coding: utf-8 -*-
"""Utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NTpcve-lgnWOqfJO4fxouTlLgyyUPv4C
"""

import os
import joblib
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier


MODEL_PATH = "models/novapay_fraud_model_rf.pkl"
FEATURES_PATH = "nmodels/ovapay_feature_columns.pkl"

# ----------------------------
# Loading/training helpers
# ----------------------------
def load_model_if_exists():
    if os.path.exists(MODEL_PATH) and os.path.exists(FEATURES_PATH):
        model = joblib.load(MODEL_PATH)
        features = joblib.load(FEATURES_PATH)
        return model, features, True
    return None, None, False


def train_rf_from_feature_file(feature_csv_path: str, target_col: str = "is_fraud"):
    df = pd.read_csv(feature_csv_path)

    if target_col not in df.columns:
        raise ValueError(f"Target column '{target_col}' not found in {feature_csv_path}")

    X = df.drop(columns=[target_col])
    y = df[target_col].astype(int)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=0.2,
        random_state=42,
        stratify=y
    )

    rf = RandomForestClassifier(
        n_estimators=500,
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        n_jobs=-1,
        class_weight="balanced",
        random_state=42
    )
    rf.fit(X_train, y_train)

    # Save
    joblib.dump(rf, MODEL_PATH)
    joblib.dump(list(X.columns), FEATURES_PATH)

    return rf, list(X.columns), (X_train, X_test, y_train, y_test)


def align_features(df_in: pd.DataFrame, feature_columns: list):
    # Keep only known columns, create missing ones as 0, and enforce ordering
    aligned = df_in.reindex(columns=feature_columns, fill_value=0)
    return aligned


def score_df(df_any: pd.DataFrame, model, feature_columns: list, threshold: float = 0.4):
    X = align_features(df_any, feature_columns)
    proba = model.predict_proba(X)[:, 1]
    flag = (proba >= threshold).astype(int)

    out = df_any.copy()
    out["fraud_probability"] = proba
    out["fraud_flag"] = flag

    # Risk tiering for a nicer UI
    out["risk_tier"] = pd.cut(
        out["fraud_probability"],
        bins=[-0.01, 0.25, 0.50, 0.75, 1.01],
        labels=["Low", "Medium", "High", "Critical"]
    )

    return out


# ----------------------------
# AI-ish assistant helpers (rule-based)
# ----------------------------
def generate_action_recommendation(row: pd.Series):
    """
    Human-friendly recommendations based on common fraud signals.
    Works even without SHAP.
    """
    reasons = []
    actions = []

    # Safe checks (columns may not exist)
    def get(col, default=None):
        return row[col] if col in row.index else default

    ip_risk = get("ip_risk_score", None)
    dts = get("device_trust_score", None)
    v24 = get("txn_velocity_24h", None)
    v1 = get("txn_velocity_1h", None)
    age = get("account_age_days", None)
    mismatch = get("location_mismatch", None)
    corridor = get("corridor_risk", None)
    new_device = get("new_device", None)

    if ip_risk is not None and ip_risk >= 0.7:
        reasons.append("High IP risk score")
        actions.append("Trigger step-up verification (OTP / 2FA) and validate IP reputation.")

    if dts is not None and dts <= 0.2:
        reasons.append("Low device trust score")
        actions.append("Require device verification and review device fingerprint history.")

    if v24 is not None and v24 >= 6:
        reasons.append("High 24h transaction velocity")
        actions.append("Temporarily throttle transfers and request additional verification.")

    if v1 is not None and v1 >= 3:
        reasons.append("Burst activity in the last hour")
        actions.append("Flag for real-time review; consider short cooldown before approving.")

    if age is not None and age <= 14:
        reasons.append("Very new account")
        actions.append("Apply stricter limits and require enhanced KYC checks.")

    if mismatch is True:
        reasons.append("Location mismatch detected")
        actions.append("Confirm customer location and require step-up authentication.")

    if corridor is not None and corridor >= 0.6:
        reasons.append("High-risk transfer corridor")
        actions.append("Route to compliance review for cross-border risk validation.")

    if new_device is True:
        reasons.append("Transaction from a new device")
        actions.append("Request device confirmation and block if pattern repeats.")

    if not reasons:
        reasons.append("No extreme red flags detected from the key risk signals.")
        actions.append("Allow transaction but keep monitoring risk trends.")

    return reasons, actions